export default () => ({
  port: parseInt(process.env.PORT || '3333', 10),
  loan_back_offic_mongo_url: process.env.LOAN_BACK_OFFICE_MONGODB_URL,
  dante_mongo_url: process.env.DANTE_MONGODB_URL,
  test_mongodb_url: process.env.TEST_MONGODB_URL,
  mongo_server_selection_timeout: process.env.MONGO_SERVER_SELECTION_TIMEOUT,
  mongo_socket_timeout: process.env.MONGO_SOCKET_TIMEOUT,
  iamBaseUrl: process.env.IAM_BASE_URL,
  clientId: process.env.CLIENT_ID,
  cientSecret: process.env.CLIENT_SECRET,
  finopnsClientId: process.env.FINOPS_CLIENT_ID,
  finopnsClientSecret: process.env.FINOPS_CLIENT_SECRET,
  elastic_apm_service_name: process.env.ELASTIC_APM_SERVICE_NAME,
  elastic_apm_secret_token: process.env.ELASTIC_APM_SECRET_TOKEN,
  elastic_apm_service_url: process.env.ELASTIC_APM_SERVER_URL,
  sentryDSN: process.env.SENTRY_DSN,
  crmBaseUrl: process.env.CRM_BASE_URL,
  elasticsearchNode: process.env.ELASTICSEARCH_NODE,
  aclCollectionName: process.env.ACL_COLLECTION_NAME,
  aclDatabaseName: process.env.ACL_DATABASE,
  aclAdminClientId: process.env.ACL_ADMIN_CLIENT_ID,
  aclRedisNodes: process.env.ACL_REDIS_NODES,
  aclIsOptional: process.env.ACL_IS_OPTIONAL,
  aclIsRedisOptional: process.env.ACL_IS_REDIS_OPTIONAL,
  sepBaseURL: process.env.SEP_BASE_URL,
  sepPackageAPI: process.env.SEP_PACKAGE_API,
  gateWayElasticIndex: process.env.ELASTICSEARCH_INDEX,
  loanBaseUrl: process.env.LOAN_BASE_URL,
  loanDetailInstallmentPath: process.env.LOAN_DETAIL_INSTALLMENT_PATH,
  minioPublicBaseUrl: process.env.MINIO_PUBLIC_BASE_URL,
  thirdParty: {
    cardListApi: process.env.THIRD_PARTY_CARD_LIST_API,
    accountListApi: process.env.THIRD_PARTY_ACCOUNT_LIST_API,
  },
});
